services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: toggl_py:dev
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    volumes:
      - ./:/home/compiler/toggl-py
