services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: toggl_py:dev
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    env_file:
      - .env
    volumes:
      - ./:/home/compiler/toggl-py
      - ./toggl_py:$CODEGEN_TARGET

  docs:
    image: toggl_py:dev
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8001"
    env_file:
      - .env
    ports:
      - "8001"
    volumes:
      - ./toggl_py:/docs
    working_dir: /docs

  codegen:
    image: toggl_py:dev
    entrypoint: /bin/bash
    env_file:
      - .env
    command: codegen/bin/run.sh
    volumes:
      - ./:/home/compiler/toggl-py
      - ./toggl_py:$CODEGEN_TARGET

  package:
    image: toggl_py:dev
    entrypoint: /bin/bash
    env_file:
      - .env
    command: codegen/bin/package.sh
    volumes:
      - ./:/home/compiler/toggl-py
