"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

from __future__ import annotations  # noqa: F401
import pprint
import re  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any

from toggl.configuration import Configuration


class ClientsReportClient:
    """
    Attributes:
      swagger_types (dict): The key is attr name
                            and the value is attr type.
      attribute_map (dict): The key is attr name
                            and the value is json key in definition.
    """

    swagger_types = {"billable_seconds": "int", "client_id": "int", "earnings": "int", "name": "str", "total_seconds": "int"}

    attribute_map = {
        "billable_seconds": "billable_seconds",
        "client_id": "client_id",
        "earnings": "earnings",
        "name": "name",
        "total_seconds": "total_seconds",
    }

    def __init__(
        self,
        billable_seconds: int = None,
        client_id: int = None,
        earnings: int = None,
        name: str = None,
        total_seconds: int = None,
        _configuration: Configuration = None,  # noqa: E501
    ):
        """
        ClientsReportClient - a model defined in Swagger

        Parameters:
          billable_seconds (int): Optional
          client_id (int): Optional
          earnings (int): Optional
          name (str): Optional
          total_seconds (int): Optional
        """
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._billable_seconds = None
        self._client_id = None
        self._earnings = None
        self._name = None
        self._total_seconds = None
        self.discriminator = None

        if billable_seconds is not None:
            self.billable_seconds = billable_seconds
        if client_id is not None:
            self.client_id = client_id
        if earnings is not None:
            self.earnings = earnings
        if name is not None:
            self.name = name
        if total_seconds is not None:
            self.total_seconds = total_seconds

    @property
    def billable_seconds(self) -> int:
        """Gets the billable_seconds of this ClientsReportClient.  # noqa: E501


        :return: The billable_seconds of this ClientsReportClient.  # noqa: E501
        :rtype: int
        """
        return self._billable_seconds

    @billable_seconds.setter
    def billable_seconds(self, billable_seconds: int):
        """Sets the billable_seconds of this ClientsReportClient.


        :param billable_seconds: The billable_seconds of this ClientsReportClient.  # noqa: E501
        :type: int
        """

        self._billable_seconds = billable_seconds

    @property
    def client_id(self) -> int:
        """Gets the client_id of this ClientsReportClient.  # noqa: E501


        :return: The client_id of this ClientsReportClient.  # noqa: E501
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: int):
        """Sets the client_id of this ClientsReportClient.


        :param client_id: The client_id of this ClientsReportClient.  # noqa: E501
        :type: int
        """

        self._client_id = client_id

    @property
    def earnings(self) -> int:
        """Gets the earnings of this ClientsReportClient.  # noqa: E501


        :return: The earnings of this ClientsReportClient.  # noqa: E501
        :rtype: int
        """
        return self._earnings

    @earnings.setter
    def earnings(self, earnings: int):
        """Sets the earnings of this ClientsReportClient.


        :param earnings: The earnings of this ClientsReportClient.  # noqa: E501
        :type: int
        """

        self._earnings = earnings

    @property
    def name(self) -> str:
        """Gets the name of this ClientsReportClient.  # noqa: E501


        :return: The name of this ClientsReportClient.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ClientsReportClient.


        :param name: The name of this ClientsReportClient.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def total_seconds(self) -> int:
        """Gets the total_seconds of this ClientsReportClient.  # noqa: E501


        :return: The total_seconds of this ClientsReportClient.  # noqa: E501
        :rtype: int
        """
        return self._total_seconds

    @total_seconds.setter
    def total_seconds(self, total_seconds: int):
        """Sets the total_seconds of this ClientsReportClient.


        :param total_seconds: The total_seconds of this ClientsReportClient.  # noqa: E501
        :type: int
        """

        self._total_seconds = total_seconds

    def to_dict(self) -> dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item, value.items())
                )
            else:
                result[attr] = value
        if issubclass(ClientsReportClient, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientsReportClient):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ClientsReportClient):
            return True

        return self.to_dict() != other.to_dict()
