"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pprint
import re  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any

from toggl.configuration import Configuration


class ModelsTimeEntrySharedWith:
    """
    Attributes:
      swagger_types (dict): The key is attr name
                            and the value is attr type.
      attribute_map (dict): The key is attr name
                            and the value is json key in definition.
    """

    swagger_types = {"accepted": "bool", "user_id": "int", "user_name": "str"}

    attribute_map = {"accepted": "accepted", "user_id": "user_id", "user_name": "user_name"}

    def __init__(
        self,
        accepted: bool = None,
        user_id: int = None,
        user_name: str = None,
        _configuration: Configuration = None,  # noqa: E501
    ):
        """
        ModelsTimeEntrySharedWith - a model defined in Swagger

        Parameters:
          accepted (bool): Optional
          user_id (int): Optional
          user_name (str): Optional
        """
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._accepted = None
        self._user_id = None
        self._user_name = None
        self.discriminator = None

        if accepted is not None:
            self.accepted = accepted
        if user_id is not None:
            self.user_id = user_id
        if user_name is not None:
            self.user_name = user_name

    @property
    def accepted(self) -> bool:
        """Gets the accepted of this ModelsTimeEntrySharedWith.  # noqa: E501


        :return: The accepted of this ModelsTimeEntrySharedWith.  # noqa: E501
        :rtype: bool
        """
        return self._accepted

    @accepted.setter
    def accepted(self, accepted: bool):
        """Sets the accepted of this ModelsTimeEntrySharedWith.


        :param accepted: The accepted of this ModelsTimeEntrySharedWith.  # noqa: E501
        :type: bool
        """

        self._accepted = accepted

    @property
    def user_id(self) -> int:
        """Gets the user_id of this ModelsTimeEntrySharedWith.  # noqa: E501


        :return: The user_id of this ModelsTimeEntrySharedWith.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this ModelsTimeEntrySharedWith.


        :param user_id: The user_id of this ModelsTimeEntrySharedWith.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def user_name(self) -> str:
        """Gets the user_name of this ModelsTimeEntrySharedWith.  # noqa: E501


        :return: The user_name of this ModelsTimeEntrySharedWith.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this ModelsTimeEntrySharedWith.


        :param user_name: The user_name of this ModelsTimeEntrySharedWith.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    def to_dict(self) -> dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item, value.items())
                )
            else:
                result[attr] = value
        if issubclass(ModelsTimeEntrySharedWith, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsTimeEntrySharedWith):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModelsTimeEntrySharedWith):
            return True

        return self.to_dict() != other.to_dict()
