"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

from __future__ import annotations  # noqa: F401
import pprint
import re  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any

from toggl.configuration import Configuration


class ModelsGoal:
    """
    Attributes:
      swagger_types (dict): The key is attr name
                            and the value is attr type.
      attribute_map (dict): The key is attr name
                            and the value is json key in definition.
    """

    swagger_types = {
        "archived_at": "str",
        "created_at": "str",
        "deleted_at": "str",
        "description": "str",
        "end": "str",
        "icon": "int",
        "icon_color": "str",
        "id": "int",
        "name": "str",
        "start": "str",
        "type": "str",
        "user_id": "int",
        "workspace_id": "int",
    }

    attribute_map = {
        "archived_at": "archivedAt",
        "created_at": "createdAt",
        "deleted_at": "deletedAt",
        "description": "description",
        "end": "end",
        "icon": "icon",
        "icon_color": "iconColor",
        "id": "id",
        "name": "name",
        "start": "start",
        "type": "type",
        "user_id": "userID",
        "workspace_id": "workspaceID",
    }

    def __init__(
        self,
        archived_at: str = None,
        created_at: str = None,
        deleted_at: str = None,
        description: str = None,
        end: str = None,
        icon: int = None,
        icon_color: str = None,
        id: int = None,
        name: str = None,
        start: str = None,
        type: str = None,
        user_id: int = None,
        workspace_id: int = None,
        _configuration: Configuration = None,  # noqa: E501
    ):
        """
        ModelsGoal - a model defined in Swagger

        Parameters:
          archived_at (str): Optional
          created_at (str): Optional
          deleted_at (str): Optional
          description (str): Optional
          end (str): Optional
          icon (int): Optional
          icon_color (str): Optional
          id (int): Optional
          name (str): Optional
          start (str): Optional
          type (str): Optional
          user_id (int): Optional
          workspace_id (int): Optional
        """
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._archived_at = None
        self._created_at = None
        self._deleted_at = None
        self._description = None
        self._end = None
        self._icon = None
        self._icon_color = None
        self._id = None
        self._name = None
        self._start = None
        self._type = None
        self._user_id = None
        self._workspace_id = None
        self.discriminator = None

        if archived_at is not None:
            self.archived_at = archived_at
        if created_at is not None:
            self.created_at = created_at
        if deleted_at is not None:
            self.deleted_at = deleted_at
        if description is not None:
            self.description = description
        if end is not None:
            self.end = end
        if icon is not None:
            self.icon = icon
        if icon_color is not None:
            self.icon_color = icon_color
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if start is not None:
            self.start = start
        if type is not None:
            self.type = type
        if user_id is not None:
            self.user_id = user_id
        if workspace_id is not None:
            self.workspace_id = workspace_id

    @property
    def archived_at(self) -> str:
        """Gets the archived_at of this ModelsGoal.  # noqa: E501


        :return: The archived_at of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._archived_at

    @archived_at.setter
    def archived_at(self, archived_at: str):
        """Sets the archived_at of this ModelsGoal.


        :param archived_at: The archived_at of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._archived_at = archived_at

    @property
    def created_at(self) -> str:
        """Gets the created_at of this ModelsGoal.  # noqa: E501


        :return: The created_at of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this ModelsGoal.


        :param created_at: The created_at of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def deleted_at(self) -> str:
        """Gets the deleted_at of this ModelsGoal.  # noqa: E501


        :return: The deleted_at of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at: str):
        """Sets the deleted_at of this ModelsGoal.


        :param deleted_at: The deleted_at of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._deleted_at = deleted_at

    @property
    def description(self) -> str:
        """Gets the description of this ModelsGoal.  # noqa: E501


        :return: The description of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ModelsGoal.


        :param description: The description of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def end(self) -> str:
        """Gets the end of this ModelsGoal.  # noqa: E501


        :return: The end of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._end

    @end.setter
    def end(self, end: str):
        """Sets the end of this ModelsGoal.


        :param end: The end of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._end = end

    @property
    def icon(self) -> int:
        """Gets the icon of this ModelsGoal.  # noqa: E501


        :return: The icon of this ModelsGoal.  # noqa: E501
        :rtype: int
        """
        return self._icon

    @icon.setter
    def icon(self, icon: int):
        """Sets the icon of this ModelsGoal.


        :param icon: The icon of this ModelsGoal.  # noqa: E501
        :type: int
        """

        self._icon = icon

    @property
    def icon_color(self) -> str:
        """Gets the icon_color of this ModelsGoal.  # noqa: E501


        :return: The icon_color of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._icon_color

    @icon_color.setter
    def icon_color(self, icon_color: str):
        """Sets the icon_color of this ModelsGoal.


        :param icon_color: The icon_color of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._icon_color = icon_color

    @property
    def id(self) -> int:
        """Gets the id of this ModelsGoal.  # noqa: E501


        :return: The id of this ModelsGoal.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ModelsGoal.


        :param id: The id of this ModelsGoal.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ModelsGoal.  # noqa: E501


        :return: The name of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ModelsGoal.


        :param name: The name of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def start(self) -> str:
        """Gets the start of this ModelsGoal.  # noqa: E501


        :return: The start of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start: str):
        """Sets the start of this ModelsGoal.


        :param start: The start of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._start = start

    @property
    def type(self) -> str:
        """Gets the type of this ModelsGoal.  # noqa: E501


        :return: The type of this ModelsGoal.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ModelsGoal.


        :param type: The type of this ModelsGoal.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def user_id(self) -> int:
        """Gets the user_id of this ModelsGoal.  # noqa: E501


        :return: The user_id of this ModelsGoal.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this ModelsGoal.


        :param user_id: The user_id of this ModelsGoal.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def workspace_id(self) -> int:
        """Gets the workspace_id of this ModelsGoal.  # noqa: E501


        :return: The workspace_id of this ModelsGoal.  # noqa: E501
        :rtype: int
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id: int):
        """Sets the workspace_id of this ModelsGoal.


        :param workspace_id: The workspace_id of this ModelsGoal.  # noqa: E501
        :type: int
        """

        self._workspace_id = workspace_id

    def to_dict(self) -> dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item, value.items())
                )
            else:
                result[attr] = value
        if issubclass(ModelsGoal, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelsGoal):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModelsGoal):
            return True

        return self.to_dict() != other.to_dict()
