"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pprint
import re  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any

from toggl.configuration import Configuration


class ProjectPatchInput:
    """
    Attributes:
      swagger_types (dict): The key is attr name
                            and the value is attr type.
      attribute_map (dict): The key is attr name
                            and the value is json key in definition.
    """

    swagger_types = {"op": "str", "path": "str", "value": "object"}

    attribute_map = {"op": "op", "path": "path", "value": "value"}

    def __init__(
        self, op: str = None, path: str = None, value: object = None, _configuration: Configuration = None  # noqa: E501
    ):
        """
        ProjectPatchInput - a model defined in Swagger

        Parameters:
          op (str): Optional
          path (str): Optional
          value (object): Optional
        """
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._op = None
        self._path = None
        self._value = None
        self.discriminator = None

        if op is not None:
            self.op = op
        if path is not None:
            self.path = path
        if value is not None:
            self.value = value

    @property
    def op(self) -> str:
        """Gets the op of this ProjectPatchInput.  # noqa: E501

        Patch operation to perform, one of \"add\", \"remove\", \"replace\"  # noqa: E501

        :return: The op of this ProjectPatchInput.  # noqa: E501
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op: str):
        """Sets the op of this ProjectPatchInput.

        Patch operation to perform, one of \"add\", \"remove\", \"replace\"  # noqa: E501

        :param op: The op of this ProjectPatchInput.  # noqa: E501
        :type: str
        """

        self._op = op

    @property
    def path(self) -> str:
        """Gets the path of this ProjectPatchInput.  # noqa: E501

        Path to the field to patch, example: \"/color\"  # noqa: E501

        :return: The path of this ProjectPatchInput.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this ProjectPatchInput.

        Path to the field to patch, example: \"/color\"  # noqa: E501

        :param path: The path of this ProjectPatchInput.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def value(self) -> object:
        """Gets the value of this ProjectPatchInput.  # noqa: E501

        Value to set when operation is \"add\" or \"replace\", example: \"#000000\". The value type actually depends on the field being patched.  # noqa: E501

        :return: The value of this ProjectPatchInput.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this ProjectPatchInput.

        Value to set when operation is \"add\" or \"replace\", example: \"#000000\". The value type actually depends on the field being patched.  # noqa: E501

        :param value: The value of this ProjectPatchInput.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self) -> dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item, value.items())
                )
            else:
                result[attr] = value
        if issubclass(ProjectPatchInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectPatchInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectPatchInput):
            return True

        return self.to_dict() != other.to_dict()
