"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pprint
import re  # noqa: F401
from datetime import datetime  # noqa: F401
from typing import Any

from toggl.configuration import Configuration


class ProjectRecurringParameters:
    """
    Attributes:
      swagger_types (dict): The key is attr name
                            and the value is attr type.
      attribute_map (dict): The key is attr name
                            and the value is json key in definition.
    """

    swagger_types = {"custom_period": "int", "period": "str", "project_start_date": "str"}

    attribute_map = {"custom_period": "custom_period", "period": "period", "project_start_date": "project_start_date"}

    def __init__(
        self,
        custom_period: int = None,
        period: str = None,
        project_start_date: str = None,
        _configuration: Configuration = None,  # noqa: E501
    ):
        """
        ProjectRecurringParameters - a model defined in Swagger

        Parameters:
          custom_period (int): Optional
          period (str): Optional
          project_start_date (str): Optional
        """
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._custom_period = None
        self._period = None
        self._project_start_date = None
        self.discriminator = None

        if custom_period is not None:
            self.custom_period = custom_period
        if period is not None:
            self.period = period
        if project_start_date is not None:
            self.project_start_date = project_start_date

    @property
    def custom_period(self) -> int:
        """Gets the custom_period of this ProjectRecurringParameters.  # noqa: E501

        Recurring custom period, the \"period\" field must be \"custom\"  # noqa: E501

        :return: The custom_period of this ProjectRecurringParameters.  # noqa: E501
        :rtype: int
        """
        return self._custom_period

    @custom_period.setter
    def custom_period(self, custom_period: int):
        """Sets the custom_period of this ProjectRecurringParameters.

        Recurring custom period, the \"period\" field must be \"custom\"  # noqa: E501

        :param custom_period: The custom_period of this ProjectRecurringParameters.  # noqa: E501
        :type: int
        """

        self._custom_period = custom_period

    @property
    def period(self) -> str:
        """Gets the period of this ProjectRecurringParameters.  # noqa: E501

        Recurring period, example \"monthly\"  # noqa: E501

        :return: The period of this ProjectRecurringParameters.  # noqa: E501
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period: str):
        """Sets the period of this ProjectRecurringParameters.

        Recurring period, example \"monthly\"  # noqa: E501

        :param period: The period of this ProjectRecurringParameters.  # noqa: E501
        :type: str
        """

        self._period = period

    @property
    def project_start_date(self) -> str:
        """Gets the project_start_date of this ProjectRecurringParameters.  # noqa: E501

        Recurring start date  # noqa: E501

        :return: The project_start_date of this ProjectRecurringParameters.  # noqa: E501
        :rtype: str
        """
        return self._project_start_date

    @project_start_date.setter
    def project_start_date(self, project_start_date: str):
        """Sets the project_start_date of this ProjectRecurringParameters.

        Recurring start date  # noqa: E501

        :param project_start_date: The project_start_date of this ProjectRecurringParameters.  # noqa: E501
        :type: str
        """

        self._project_start_date = project_start_date

    def to_dict(self) -> dict[str, Any]:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item, value.items())
                )
            else:
                result[attr] = value
        if issubclass(ProjectRecurringParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectRecurringParameters):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectRecurringParameters):
            return True

        return self.to_dict() != other.to_dict()
