"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pytest

import toggl  # noqa: F401
from toggl.api.groups_api import GroupsApi
from toggl.rest import ApiException  # noqa: F401


@pytest.fixture
def api():
    return GroupsApi()


def test_GroupsApi_delete_organization_group(api):
    """Test case for delete_organization_group

    Deletes group  # noqa: E501
    """
    response = api.delete_organization_group()

    assert response


def test_GroupsApi_delete_project_group(api):
    """Test case for delete_project_group

    Remove project group.  # noqa: E501
    """
    response = api.delete_project_group()

    assert response


def test_GroupsApi_delete_workspace_group(api):
    """Test case for delete_workspace_group

    Delete group  # noqa: E501
    """
    response = api.delete_workspace_group()

    assert response


def test_GroupsApi_get_organization_groups(api):
    """Test case for get_organization_groups

    List of groups in organization with user and workspace assignments  # noqa: E501
    """
    response = api.get_organization_groups()

    assert response


def test_GroupsApi_get_organization_workspaces_groups(api):
    """Test case for get_organization_workspaces_groups

    List of groups in a workspace within an organization with user assignments.  # noqa: E501
    """
    response = api.get_organization_workspaces_groups()

    assert response


def test_GroupsApi_get_project_groups(api):
    """Test case for get_project_groups

    Get workspace project groups.  # noqa: E501
    """
    response = api.get_project_groups()

    assert response


def test_GroupsApi_get_workspace_groups(api):
    """Test case for get_workspace_groups

    Get workspace groups  # noqa: E501
    """
    response = api.get_workspace_groups()

    assert response


def test_GroupsApi_patch_organization_group(api):
    """Test case for patch_organization_group

    Patch group  # noqa: E501
    """
    response = api.patch_organization_group()

    assert response


def test_GroupsApi_post_organization_group(api):
    """Test case for post_organization_group

    Create group  # noqa: E501
    """
    response = api.post_organization_group()

    assert response


def test_GroupsApi_post_project_group(api):
    """Test case for post_project_group

    Adds group to project.  # noqa: E501
    """
    response = api.post_project_group()

    assert response


def test_GroupsApi_post_workspace_group(api):
    """Test case for post_workspace_group

    Create group  # noqa: E501
    """
    response = api.post_workspace_group()

    assert response


def test_GroupsApi_put_organization_group(api):
    """Test case for put_organization_group

    Edit group  # noqa: E501
    """
    response = api.put_organization_group()

    assert response


def test_GroupsApi_put_organization_workspaces_assignments(api):
    """Test case for put_organization_workspaces_assignments

    Change assignments of users within a workspace.  # noqa: E501
    """
    response = api.put_organization_workspaces_assignments()

    assert response


def test_GroupsApi_put_workspace_group(api):
    """Test case for put_workspace_group

    Update group  # noqa: E501
    """
    response = api.put_workspace_group()

    assert response
