"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pytest

import toggl  # noqa: F401
from toggl.api.reports_api_v3 import ReportsApiv3
from toggl.rest import ApiException  # noqa: F401


@pytest.fixture
def api():
    return ReportsApiv3()


def test_ReportsApiv3_action_tasks_auth_post(api):
    """Test case for action_tasks_auth_post

    List tasks  # noqa: E501
    """
    pass


def test_ReportsApiv3_action_tasks_post(api):
    """Test case for action_tasks_post

    List tasks  # noqa: E501
    """
    pass


def test_ReportsApiv3_comparative_post(api):
    """Test case for comparative_post

    Load comparative report  # noqa: E501
    """
    pass


def test_ReportsApiv3_data_trends_clients_post(api):
    """Test case for data_trends_clients_post

    Load clients' data trends  # noqa: E501
    """
    pass


def test_ReportsApiv3_data_trends_projects_post(api):
    """Test case for data_trends_projects_post

    Load projects' data trends  # noqa: E501
    """
    pass


def test_ReportsApiv3_data_trends_users_post(api):
    """Test case for data_trends_users_post

    Load users' data trends  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_clients_post(api):
    """Test case for filters_clients_post

    List clients  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_project_groups_post(api):
    """Test case for filters_project_groups_post

    List project groups filter  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_project_users_post(api):
    """Test case for filters_project_users_post

    List project users  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_projects_post(api):
    """Test case for filters_projects_post

    List projects  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_projects_status_post(api):
    """Test case for filters_projects_status_post

    List projects statuses  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_tasks_auth_status_post(api):
    """Test case for filters_tasks_auth_status_post

    List tasks statuses  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_tasks_status_post(api):
    """Test case for filters_tasks_status_post

    List tasks statuses  # noqa: E501
    """
    pass


def test_ReportsApiv3_filters_users_post(api):
    """Test case for filters_users_post

    List users  # noqa: E501
    """
    pass


def test_ReportsApiv3_profitability_projects_post(api):
    """Test case for profitability_projects_post

    Load profitability projects report  # noqa: E501
    """
    pass


def test_ReportsApiv3_search_clients_post(api):
    """Test case for search_clients_post

    Search clients  # noqa: E501
    """
    pass


def test_ReportsApiv3_search_projects_post(api):
    """Test case for search_projects_post

    List projects  # noqa: E501
    """
    pass


def test_ReportsApiv3_search_users_post(api):
    """Test case for search_users_post

    List users  # noqa: E501
    """
    pass
