"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pytest

import toggl  # noqa: F401
from toggl.api.workspaceslogo_api import WorkspaceslogoApi
from toggl.rest import ApiException  # noqa: F401


@pytest.fixture
def api():
    return WorkspaceslogoApi()


def test_WorkspaceslogoApi_get_workspace_logo(api):
    """Test case for get_workspace_logo

    Get workspace logo  # noqa: E501
    """
    response = api.get_workspace_logo()

    assert response


def test_WorkspaceslogoApi_get_workspace_logo_0(api):
    """Test case for get_workspace_logo_0

    Delete workspace logo  # noqa: E501
    """
    response = api.get_workspace_logo_0()

    assert response


def test_WorkspaceslogoApi_post_workspace_logo(api):
    """Test case for post_workspace_logo

    Post workspace logo  # noqa: E501
    """
    response = api.post_workspace_logo()

    assert response
