"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pytest

import toggl  # noqa: F401
from toggl.api.organizationscustomer_api import OrganizationscustomerApi
from toggl.rest import ApiException  # noqa: F401


@pytest.fixture
def api():
    return OrganizationscustomerApi()


def test_OrganizationscustomerApi_get_organization_customer(api):
    """Test case for get_organization_customer

    Customer  # noqa: E501
    """
    pass


def test_OrganizationscustomerApi_get_unified_customer(api):
    """Test case for get_unified_customer

    Retrieve unified customer  # noqa: E501
    """
    pass


def test_OrganizationscustomerApi_post_organization_customer(api):
    """Test case for post_organization_customer

    ContactDetails  # noqa: E501
    """
    pass


def test_OrganizationscustomerApi_post_unified_customer(api):
    """Test case for post_unified_customer

    Create unified customer  # noqa: E501
    """
    pass


def test_OrganizationscustomerApi_put_unified_customer(api):
    """Test case for put_unified_customer

    Update unified customer  # noqa: E501
    """
    pass
