"""
Public Toggl API. Note: We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`. In our case it will be `base64(user_name:api_token)`.  # noqa: E501

This file is auto generated by the swagger code generator program.
Do not edit this file manually.

OpenAPI spec version: 9
Generated by: https://github.com/compilerla/toggl-py
"""

import pytest

import toggl  # noqa: F401
from toggl.api.tasks_api import TasksApi
from toggl.rest import ApiException  # noqa: F401


@pytest.fixture
def api():
    return TasksApi()


def test_TasksApi_delete_workspace_project_task(api):
    """Test case for delete_workspace_project_task

    WorkspaceProjectTask  # noqa: E501
    """
    pass


def test_TasksApi_get_workspace_project_task(api):
    """Test case for get_workspace_project_task

    WorkspaceProjectTask  # noqa: E501
    """
    pass


def test_TasksApi_get_workspace_project_tasks(api):
    """Test case for get_workspace_project_tasks

    WorkspaceProjectTasks  # noqa: E501
    """
    pass


def test_TasksApi_get_workspace_tasks(api):
    """Test case for get_workspace_tasks

    Tasks  # noqa: E501
    """
    pass


def test_TasksApi_patch_workspace_project_tasks(api):
    """Test case for patch_workspace_project_tasks

    WorkspaceProjectTasks  # noqa: E501
    """
    pass


def test_TasksApi_post_workspace_project_tasks(api):
    """Test case for post_workspace_project_tasks

    WorkspaceProjectTasks  # noqa: E501
    """
    pass


def test_TasksApi_put_workspace_project_task(api):
    """Test case for put_workspace_project_task

    WorkspaceProjectTask  # noqa: E501
    """
    pass
