name: MkDocs Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "toggl_py/docs/**"
      - "toggl_py/mkdocs.yml"

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/pytest.yml

  mkdocs:
    name: Publish docs
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: toggl_py/docs/coverage

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          REQUIREMENTS: toggl_py/docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
