name: Pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Install Python dependencies
        run: pip install -e toggl_py/[test]

      - name: Run tests
        run: tests/run.sh
        working-directory: ./toggl_py

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: toggl_py/tests/coverage

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          COVERAGE_PATH: toggl_py/
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 80
